# Configuration file for ChatLinks

url: "https://join.slack.com/t/coderdojo-lx/shared_invite/zt-dq12mi5f-_DQSHXp_aq6fS0W~RPNdcw"
intro: "O Slack é onde falamos e partilhamos as nossas ideias!"
clickable: "Junta-te"
hover: "Instala a app no telemóvel também!"